### ISSUE TITLE
suggest: add demo link to hugo themes site

### ISSUE THREAD

**Issue by imba-tjd** [peaceiris/hugo-theme-iris#231]
This theme:

![图片](https://user-images.githubusercontent.com/24759802/99777169-e2f2bd80-2b4c-11eb-9ea5-c545d8c605ba.png)

while others:

![图片](https://user-images.githubusercontent.com/24759802/99777211-f00fac80-2b4c-11eb-86a1-60070b5c9bb5.png)

**Comment by peaceiris** [comment]
Oh, I have noticed that now. Thank you for reporting it.

When I published this theme on the list, the demo link was available. It became unavailable when this theme started to use Hugo modules, I think. Enabling the demo button on the gohugoio theme site is not ideal since the building step takes a long time to download all modules. We do not need the button since we have the demo site on GitHub Pages instead.

A demo site is available here: https://hugothemeiris.peaceiris.app/
